### ISSUE TITLE
No linux-arm64 python wheel

### ISSUE THREAD

**Issue by rsmh9628** [cloudflare/stpyv8#116]
There seems to be a wheel for macOS-arm64 but no linux-arm64 wheel. Adding a linux-arm64 wheel would be useful for people trying to deploy the library on a Raspberry Pi.

**Comment by buffer** [comment]
FYI Github is actively working to provide Linux ARM64 runners

https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/

Once the image will be available I will take care of adding a new workflow for that. Thanks!

**Comment by bastien8060** [comment]
Further more, I'm getting a `No module named 'settings'`

```
Collecting stpyv8
  Using cached stpyv8-12.7.224.18.tar.gz (45 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iuyx7063/stpyv8_d841dabd35204ae7b80a965d813a598e/setup.py", line 12, in <module>
          from settings import *  # pylint:disable=wildcard-import,unused-wildcard-import
      ModuleNotFoundError: No module named 'settings'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any idea what may cause this? Thanks!

**Comment by bastien8060** [comment]
Ok, nevermind, I ended up building from source- used the github worker `https://github.com/cloudflare/stpyv8/blob/master/.github/workflows/linux.yml` as a reference to download and build the v8 project, which stpyv8 depends on

**Comment by bastien8060** [comment]
@buffer what's the progress on the images? (Compiling V8 is really slow)

**Comment by griffinli** [comment]
I'm getting the `No module named 'settings'` error as well, running on a fresh install of an Ubuntu Desktop 25.04 ARM in a VM on UTM

**Comment by aykevl** [comment]
@buffer GitHub now has ARM64 hosted runners, can you take a look at this?
linux-arm64 laptops are becoming more common now (for example, I'm running Asahi Linux).
