### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by rzeydelis** [cloudflare/stpyv8#60]
Hi,

I am running this python3 file:

```
import STPyV8

with STPyV8.JSContext() as ctxt:
  output = ctxt.eval("""
import { JSBI } from "@uniswap/sdk";
import { ethers } from 'ethers';
import * as fs from 'fs';

    // ERC20 json abi file
let ERC20Abi = fs.readFileSync('Erc20.json');
const ERC20 = JSON.parse(ERC20Abi);

    // V3 pool abi json file
let pool = fs.readFileSync('V3PairAbi.json');
const IUniswapV3PoolABI = JSON.parse(pool);

    // V3 factory abi json
let facto = fs.readFileSync('V3factory.json');
const IUniswapV3FactoryABI = JSON.parse(facto);

let NFT = fs.readFileSync('UniV3NFT.json');
const IUniswapV3NFTmanagerABI = JSON.parse(NFT);

const provider = new ethers.providers.JsonRpcProvider(<INSERT ALCHEMY API ID>)

    // V3 standard addresses (different for celo)
const factory = "0x1F98431c8aD98523631AE4a59f267346ea31F984";
const NFTmanager = "0xC36442b4a4522E871399CD717aBDD847Ab11FE88";

async function getData(tokenID){
    let FactoryContract = new ethers.Contract(factory, IUniswapV3FactoryABI, provider);

    let NFTContract =  new ethers.Contract(NFTmanager, IUniswapV3NFTmanagerABI, provider);
    let position = await NFTContract.positions(tokenID);
    
    let token0contract =  new ethers.Contract(position.token0, ERC20, provider);
    let token1contract =  new ethers.Contract(position.token1, ERC20, provider);
    let token0Decimal = await token0contract.decimals();
    let token1Decimal = await token1contract.decimals();
    
    let token0sym = await token0contract.symbol();
    let token1sym = await token1contract.symbol();
    
    let V3pool = await FactoryContract.getPool(position.token0, position.token1, position.fee);
    let poolContract = new ethers.Contract(V3pool, IUniswapV3PoolABI, provider);

    let slot0 = await poolContract.slot0();

    
    let pairName = token0sym +"/"+ token1sym;
    
    let dict = {"SqrtX96" : slot0.sqrtPriceX96.toString(), "Pair": pairName, "T0d": token0Decimal, "T1d": token1Decimal, "tickLow": position.tickLower, "tickHigh": position.tickUpper, "liquidity": position.liquidity.toString()}

    return dict
}


const Q96 = JSBI.exponentiate(JSBI.BigInt(2), JSBI.BigInt(96));
const MIN_TICK = -887272;
const MAX_TICK = 887272;

function getTickAtSqrtRatio(sqrtPriceX96){
    let tick = Math.floor(Math.log((sqrtPriceX96/Q96)**2)/Math.log(1.0001));
    return tick;
}

async function getTokenAmounts(liquidity,sqrtPriceX96,tickLow,tickHigh,token0Decimal,token1Decimal){
    let sqrtRatioA = Math.sqrt(1.0001**tickLow).toFixed(18);
    let sqrtRatioB = Math.sqrt(1.0001**tickHigh).toFixed(18);
    let currentTick = getTickAtSqrtRatio(sqrtPriceX96);
    let sqrtPrice = sqrtPriceX96 / Q96;
    let amount0wei = 0;
    let amount1wei = 0;
    if(currentTick <= tickLow){
        amount0wei = Math.floor(liquidity*((sqrtRatioB-sqrtRatioA)/(sqrtRatioA*sqrtRatioB)));
    }
    if(currentTick > tickHigh){
        amount1wei = Math.floor(liquidity*(sqrtRatioB-sqrtRatioA));
    }
    if(currentTick >= tickLow && currentTick < tickHigh){ 
        amount0wei = Math.floor(liquidity*((sqrtRatioB-sqrtPrice)/(sqrtPrice*sqrtRatioB)));
        amount1wei = Math.floor(liquidity*(sqrtPrice-sqrtRatioA));
    }
    
    let amount0Human = (amount0wei/(10**token0Decimal)).toFixed(token0Decimal);
    let amount1Human = (amount1wei/(10**token1Decimal)).toFixed(token1Decimal);

    console.log("Amount Token0 wei: "+amount0wei);
    console.log("Amount Token1 wei: "+amount1wei);
    console.log("Amount Token0 : "+amount0Human);
    console.log("Amount Token1 : "+amount1Human);
    return [amount0wei, amount1wei]
}

async function start(positionID){
    let data = await getData(positionID);
    let tokens = await getTokenAmounts(data.liquidity, data.SqrtX96, data.tickLow, data.tickHigh, data.T0d, data.T1d);
}

start(273381)
// Also it can be used without the position data if you pull the data it will work for any range
getTokenAmounts(12558033400096537032, 20259533801624375790673555415)
  """)

# output = ctxt.eval()
print(output)
```

and I am getting the following error:
```
Traceback (most recent call last):
  File "/home/bobby/uni_balances_stpyv8/main.py", line 4, in <module>
    output = ctxt.eval("""
SyntaxError: SyntaxError: Cannot use import statement outside a module (  @ 2 : 0 )  -> import { JSBI } from "@uniswap/sdk";

```

However, when I run the JavaScript file on it's own, it works and is able to pull data. I do have a `package.json` that includes the following code (this code should fix these import statements outside a module errors):

```
{
  "type": "module"
}
```

Could this error be because my JS code is not wrapped in a function?

**Comment by rzeydelis** [comment]
I potentially noticed something interesting. When I comment out the module imports (lines 6,7,8), I get the following error:

```
Traceback (most recent call last):
  File "/home/bobby/uni_balances_stpyv8/main.py", line 4, in <module>
    output = ctxt.eval("""
ReferenceError: ReferenceError: fs is not defined (  @ 8 : 15 )  -> let ERC20Abi = fs.readFileSync('Erc20.json');

```
Seems like the code is able to execute now, but obviously can't find the function `fs` because I commented it out. Is it possible that the Python file is not pulling in the `package.json` file.

**Comment by rzeydelis** [comment]
@buffer any idea?

**Comment by liran-funaro** [comment]
@rzeydelis I had the same issue. I simply embedded all files into a single string and loaded it without the `import` and `export` statements.

```python3
import re
import_regexp = re.compile(r"^(import [^\n]* from\s*[\"']([/\w_\-.]+\.js)[\"'][^\n]*;$)", re.M)

def content_of(main_folder: str, file_path: str):
    if file_path[0] == "/":
        # Make sure the file path is relative to the main folder
        file_path = file_path[1:]
    with open(os.path.join(main_folder, file_path)) as f:
        file_content = f.read()

    # Split content as follows: [content, import file, content, import file, ...]
    lines_split = import_regexp.split(file_content)
    # Merge only content parts and remove all export statements
    js_content = "".join(lines_split[::2]).replace("export ", "")
    # Fetch import file names
    import_names = lines_split[1::2]

    # First load all import content
    content = [content_of(main_folder, name) for name in import_names]
    content.append(f"// {file_path}")
    content.append(js_content)
    return "\n".join(content)
```

Then I used it as follows:
```python3
with STPyV8.JSContext() as ctxt:
    ctxt.eval(content_of("root", "js/main.js")
    ctxt.eval("some calculation script")
```

**Comment by buffer** [comment]
@rzeydelis sorry for the late reply. The solution proposed by @liran-funaro works fine but I would like to figure out the reason behind what you are observing. I can reproduce it here so at least this will give me the opportunity to investigate. I will update the issue in case I discover something relevant. Thanks!
